const router = require('express').Router();
const { body, param } = require('express-validator');
const ctrl = require('../controllers/property.controller');
const { authenticate } = require('../middlewares/auth.middleware');
const { validate }     = require('../middlewares/validate.middleware');
const { upload }       = require('../middlewares/upload.middleware');
const v = [body('name').trim().notEmpty().withMessage('Name required.'), body('location').trim().notEmpty().withMessage('Location required.'), body('city').trim().notEmpty().withMessage('City required.'), body('bhkType').trim().notEmpty().withMessage('BHK type required.'), body('price').isDecimal().withMessage('Valid price required.'), body('type').isIn(['FLAT','SHOP','PLOT','STUDIO_APARTMENT']).withMessage('Invalid type.'), body('status').isIn(['UNDER_CONSTRUCTION','READY_TO_MOVE','NEW_LAUNCH']).withMessage('Invalid status.')];
router.get('/',              ctrl.listProperties);
router.get('/:slug',         ctrl.getPropertyBySlug);
router.post('/',             authenticate, v, validate, ctrl.createProperty);
router.put('/:id',           authenticate, param('id').isInt({min:1}), v, validate, ctrl.updateProperty);
router.patch('/:id/toggle',  authenticate, param('id').isInt({min:1}), validate, ctrl.togglePropertyStatus);
router.delete('/:id',        authenticate, param('id').isInt({min:1}), validate, ctrl.deleteProperty);
router.post('/:id/images',   authenticate, param('id').isInt({min:1}), validate, upload.array('images',10), ctrl.uploadPropertyImages);
router.delete('/:id/images', authenticate, param('id').isInt({min:1}), validate, ctrl.deletePropertyImage);
module.exports = router;
